---

name: vgg16

gops: [30.960206824]
shapes:
  - [1, 3, 224, 224]

precision: true

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/vgg16-12.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --resize_dims 256,256
    --mean 123.675,116.28,103.53
    --scale 0.0171,0.0175,0.0174
    --pixel_format rgb
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(imagenet2012_mlir_cali_set)
    --input_num 100
    -o $(workdir)/$(name).calitable

deploy:
  - model_deploy.py  --mlir $(workdir)/transformed.mlir
      --quantize F32
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_$(target)_f32.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(workdir)/$(name).calitable
      --quant_input
      --quant_output
      --chip $(target)
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.98,0.79
      --model $(workdir)/$(name)_$(target)_int8_sym.bmodel

dataset:
  image_path: $(imagenet2012_val_set)
  image_label: $(imagenet2012_caffe_val_ground_truth)
  mean: [123.675, 116.28, 103.53]
  scale: [0.0171, 0.0175, 0.0174]
  resize_dims: 256
  size: 224
  trans: true
  bgr2rgb: true

BM1684:
  harness:
    type: topk
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_$(target)_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_$(target)_int8_sym.bmodel

BM1684X:
  +deploy:
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --asymmetric
        --calibration_table $(workdir)/$(name).calitable
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.98,0.94
        --model $(workdir)/$(name)_$(target)_int8_asym.bmodel

  harness:
    type: topk
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_$(target)_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_$(target)_int8_sym.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_$(target)_int8_asym.bmodel
