---

name: mtcnn_rnet
gops: 0.003

shapes:
  - [1, 3, 24, 24]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/det2.prototxt
    --model_data $(home)/det2.caffemodel
    --test_input $(root)/dataset/samples/stock_market.jpg
    --input_shapes [$(shape_param)]
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/$(name).mlir

deploy:
  - model_deploy.py  --mlir $(workdir)/$(name).mlir
    --quantize F32
    --chip $(target)
    --test_input $(workdir)/$(name)_in_f32.npz
    --test_reference $(name)_top_outputs.npz
    --tolerance 0.99,0.99
    --model $(workdir)/$(name)_$(target)_f32.bmodel
  - model_deploy.py  --mlir $(workdir)/$(name).mlir
    --quantize INT8
    --calibration_table $(home)/det2_cali_table
    --quant_input
    --quant_output
    --chip $(target)
    --test_input $(workdir)/$(name)_in_f32.npz
    --test_reference $(name)_top_outputs.npz
    --tolerance 0.93,0.50
    --model $(workdir)/$(name)_$(target)_int8_sym.bmodel

BM1684X:
  +deploy:
    - model_deploy.py --mlir $(workdir)/$(name).mlir
        --quantize F16
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.95,0.85
        --model $(workdir)/$(name)_$(target)_f16.bmodel
    - model_deploy.py --mlir $(workdir)/$(name).mlir
        --quantize BF16
        --chip $(target)
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.95,0.85
        --model $(workdir)/$(name)_$(target)_bf16.bmodel
