---

name: resnet152-v1-7
gops: [22.667994088]

shapes:
  - [1, 3, 224, 224]

precision: true

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/resnet152-v1-7.onnx
    --input_shapes [$(shape_param)]
    --resize_dims 256,256
    --mean 123.67,116.28,103.53
    --scale 0.017,0.017,0.017
    --test_input $(root)/dataset/samples/cat.jpg
    --test_result $(name)_top_outputs.npz
    --pixel_format rgb
    --keep_aspect_ratio
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(imagenet2012_mlir_cali_set)
    --input_num 100
    -o $(workdir)/cali_table

BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip bm1684x
        --tolerance 0.79,0.75
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --calibration_table $(workdir)/cali_table
        --quant_input
        --quant_output
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.78,0.42
        --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --asymmetric
        --calibration_table $(workdir)/cali_table
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.78,0.31
        --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel

  dataset:
    image_path: $(imagenet2012_val_set)
    image_label: $(imagenet2012_caffe_val_ground_truth)
    mean: [123.67, 116.28, 103.53]
    scale: [0.017, 0.017, 0.017]
    resize_dims: 256
    size: 224
    trans: True
    bgr2rgb: True

  harness:
    type: topk
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_bm1684x_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_bm1684x_int8_sym.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_bm1684x_int8_asym.bmodel
